# Generated by Django 3.0.3 on 2020-03-27 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sigla', models.CharField(max_length=10)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
                ('valor', models.FloatField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_eventos.Pessoa')),
                ('cpf', models.CharField(max_length=11)),
            ],
            bases=('app_eventos.pessoa',),
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.Evento')),
                ('ingresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.Ingresso')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.Pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='realizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.Pessoa'),
        ),
    ]
